### ISSUE TITLE
WebServer打包问题

### ISSUE THREAD

**Issue by andrewyong87** [ttpai/AndJacoco#3]
作者您好，我在本地调试您的代码时，发现WebServer打war时老是失败啊，使用idea把WebServer倒入后，该做的配置也都做了，但是打出来的war包不能用，方便提供详细的配置方法吗？

**Comment by Zihao-Wu** [comment]
我已经上传了一个war包，在WebServer 目录下，你试试，如果不行，你可以自己搞个web项目，因为web 就一个类，你可以拷过去自己修改跑起来

**Comment by andrewyong87** [comment]
clone出来的代码中找不到现成的war包，但是自己搞个web项目把代码放进去是可以的
