### ISSUE TITLE
WebServer源码中缺少download接口

### ISSUE THREAD

**Issue by andrewyong87** [ttpai/AndJacoco#5]
android studio ide中执行“generateReport"task的时候脚本会去服务的下载.ec文件，命令如下：curl -o /Users/andrew/Document/Jacoco/app_increment/AndJacoco/app/build/outputs/coverage/a5b68097-f981-49d2-bea1-f01a312a7f21_1624867436256.ec http://112.109.211.149:8080/download/comandjacocodemo/1/a5b68097-f981-49d2-bea1-f01a312a7f21_1624867436256.ec，结果下载下来的ec文件内容是“***404 not found***”，查看代码发现服务的没有“download”接口

**Comment by Zihao-Wu** [comment]
不需要download 接口，这是直接访问文件的。你看下服务端保存文件的代码，默认是保存在：~/work/server/download/，你看下有没对应的文件。

**Comment by andrewyong87** [comment]
文件是有的，但是通过curl获取的时候返回的却是404

**Comment by khchcker** [comment]
@andrewyong87 你怎么解决的呢
我也遇到类似的问题 ：在webservices 上的的ec.文件貌似有个unknow- host 
![image](https://user-images.githubusercontent.com/16751397/205640252-773d42e0-d9ae-4a66-b1e5-db3f6cf3ac37.png)
然后下载到本地 ， 打开都是404 not found
